name: Enforce Branch Name for PRs

on:
  pull_request:
    branches:
      - main
      - develop
  create:
    branches:
      - main
      - develop
jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment
        run: |
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          
      - name: Check branch name
        shell: bash
        run: |
          branch_name="${GITHUB_HEAD_REF}"
          echo "Checking branch name: $branch_name"
          
          if [[ ! "$branch_name" =~ ^(feature|bug)/[a-zA-Z0-9._-]+$ ]]; then
            echo "❌ Branch name '$branch_name' is invalid."
            echo "Allowed patterns: feature/* or bug/*"
            exit 1
          else
            echo "✅ Branch name '$branch_name' is valid."
          fi