name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge to main
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1
      
      - name: Check merge to dev
        if: github.base_ref == 'dev' && !startsWith(github.head_ref, 'feature/') && !startsWith(github.head_ref, 'bug/')
        run: |
          echo "ERROR: You can only merge to dev from feature/* or bug/* branches."
          exit 1